qqqbaseURL: "https://angelitora.github.io/"
title: Angel Ruiz-Angulo
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 1
        - name: Students
          url: students/
          weight: 2
        - name: News
          url: news/
          weight: 3
        - name: Resume
          url: RuizAngulo_CV_2024.pdf
          weight: 4
        # - name: Photography
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I am an oceanographer/biker/baker."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "March 2024"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Angel Ruiz-Angulo
          subtitle: "I am an Associate Professor in Physical Oceanography at the University of Iceland"
          imageUrl: "angel-ito.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Angel Ruiz-Angulo
          buttons:
            - name: Publications
              url: publications/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
           # - name: Newsletter
           #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            - name: Students
              url: students/
            - name: News
              url: news/
            - name: Resume
              url: RuizAngulo_CV_2024.pdf
            #- name: Archive
            #  url: archive/
    socialIcons:
        # - name: CV
        #   url: cv_rosa.pdf
        - name: Email
          url: mailto:angel@hi.is
        - name: Location
          url: location/
    
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=Lb1n85YAAAAJ&hl=en&oi=ao
        - name: LinkedIn
          url: https://www.linkedin.com/in/angel-ruiz-angulo-1160a71/
        # - name: GitHub
        #   url: https://github.com/pmichaillat
        - name: ORCID
          url: https://orcid.org/0000-0002-7292-3002
      

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Angel Ruiz-Angulo"
      icon: snail_maya.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
design:
    background:
        image:
            filename: isotherms_4_10.png
